### PR TITLE
Add support for Flatpak and Snap version of Discord

### PR DESCRIPTION
**Pull request by thecatcore**

### CODE REVIEW

**Review by caoimhebyrne — CHANGES_REQUESTED** [review]
Not sure if this is correct. The Minecraft flatpak package already forwards the required paths, and the Discord flatpak also has instructions on it. 

https://github.com/flathub/com.mojang.Minecraft/blob/master/minecraft

https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)#unsandboxed-applications

**Comment by caoimhebyrne** [comment]
I'll close this since we shouldn't do flatpak or snap specific operations.

**Comment by thecatcore** [comment]
The source for this fix is the nodejs package [@xhayper/discord-rpc](https://github.com/xhayper/discord-rpc/blob/main/src/transport/IPC.ts#L42-L65).
I'm using the flatpak version of Discord but the apps which use RPC are not flatpak themselves. Your library currently doesn't work in this case but the package linked is one of the few that does.

**Comment by DJtheRedstoner** [comment]
The Discord flatpak has instructions on what to do: https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)#unsandboxed-applications. This should not be the responsibility of individual libraries.

**Pull request closed without merging**
